[package]
name = "containify"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["sched"] }
rustix = { version = "0.38.37", features = ["thread"] }
sys-mount = "3.0.1"
